apiVersion: v1
kind: Service
metadata:
  name: ratnaker-contoso
  namespace: sample-app-namespace-1754388435138
  labels:
    app.kubernetes.io/name: ratnaker-contoso
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ratnaker-contoso
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000